#!/usr/bin/env bash

set -eau
set -o pipefail
set -x

mount_home=${HOME}/
export OLLAMA_HOST="0.0.0.0"
export OLLAMA_DEBUG=${OLLAMA_DEBUG:-1}
start() {
	${mount_bin:-}ollama serve $@
}

run() {
	${mount_bin:-}ollama run $@

}

lama() {
	${mount_bin:-}ollama $@

}

web() {
	if [[ -n "${wsl:-}" ]]; then
		source ${mount_home:-}workspace/github.com/vegerot/localllm/.venv-wsl/bin/activate
		${mount_home:-}workspace/github.com/vegerot/localllm/.venv-wsl/bin/open-webui serve $@
	fi
	source .venv/bin/activate
	open-webui serve $@
}

upgrade() {
	ollama list | tail -n +2 | awk '{print $1}' | grep -v mygptoss | xargs -I {} sh -xc 'ollama pull {}'
	if [[ -n "${wsl:-}" ]]; then
		source ${mount_home:-}workspace/github.com/vegerot/localllm/.venv-wsl/bin/activate
	fi
	source .venv/bin/activate
	uv pip install --upgrade open-webui jupyterlab ollama
	uv pip freeze > requirements.txt
	curl -fsSL https://ollama.com/install.sh | sh
	sudo systemctl stop ollama.service && sudo systemctl disable ollama.service
}

start_both() {
	start $@ &
	web $@
}

main() {

	if [[ -z "${1:-}" ]]; then
		start_both
	elif [[ "$1" = "start" ]]; then
		shift
		start $@
	elif [[ "$1" = "run" ]]; then
		shift
		run $@
	elif [[ "$1" == "web" ]]; then
		shift
		web $@
	elif [[ "$1" == "upgrade" ]]; then
		shift
		upgrade $@
	elif [[ "$1" == "wsl" ]]; then
		shift
		export mount=/mnt/wsl/PHYSICALDRIVE1p2/
		export mount_home=${mount}home/max/
		export mount_bin=${mount}usr/local/bin/
		export OLLAMA_MODELS=${mount_home}.ollama/models/
		wsl=true
		main $@
	else
		lama $@
	fi
}

main $@ |& tee -a ./ollama.log
